### ISSUE TITLE
Footer UI can be improved.

### ISSUE THREAD

**Issue by sahilsaini1107** [adithyapaib/Neomorphic-PortfolioTemplate#10]

**Comment by adithyapaib** [comment]
Sure u can do it now

**Comment by Sameer1408** [comment]
sir i have a bit experience in UI may I work on it ?

**Comment by tanvideshmukh29** [comment]
I would love to contribute on this issue ...plz assign this to me.

**Comment by Paawan9700** [comment]
hey kindly assign it to me. i will surely resolve it.

**Comment by sahilsaini110** [comment]
@Sameer1408  @Paawan9700 @tanvideshmukh29  i am working on this issue you make look for others.

**Comment by adithyapaib** [comment]
> sir i have a bit experience in UI may I work on it ?

Sure

**Comment by adithyapaib** [comment]
Assigined everyone please share the work among yourself and PR accordingly

**Comment by devikavarshney** [comment]
Hey i am a UI designer and i can work on this.
