### ISSUE TITLE
FIX the broken layout and remove the project section and improve the contact section UI

### ISSUE THREAD

**Issue by adithyapaib** [adithyapaib/Neomorphic-PortfolioTemplate#108]
FIX the broken layout and remove the project section and improve the contact section UI

**Comment by shreyaa2410** [comment]
I would like to work on this issue. please assign!

**Comment by adi611** [comment]
Please assign me this issue with Hacktoberfest label. Thanks.

**Comment by ShouryaSrivastava01** [comment]
@adithyapaib  assign me this issue please

**Comment by adithyapaib** [comment]
Done
