### ISSUE TITLE
Want to fix footer issue

### ISSUE THREAD

**Issue by komal1503** [adithyapaib/Neomorphic-PortfolioTemplate#111]
![2021-10-05 (4)](https://user-images.githubusercontent.com/76110970/136038963-cd870316-44a0-4e81-9ad8-d0fd6cbeeaae.png)

**Comment by komal1503** [comment]
Hey, @adithyapaib  I want to fix this issue and want to remove some extra elements to make it more accurate. So can I work on this issue?

**Comment by muhammadsuheer** [comment]
I fixed it 
![msedge_aE5E66NTqb](https://user-images.githubusercontent.com/58456635/136040576-4a359bab-0285-40e2-af96-fff4bd4870df.png)

**Comment by adithyapaib** [comment]
> I already fixed it and add a PR ![msedge_aE5E66NTqb](https://user-images.githubusercontent.com/58456635/136040576-4a359bab-0285-40e2-af96-fff4bd4870df.png)

Merage conflicts

**Comment by Gaurav6291** [comment]
hello @adithyapaib sir, I am currently learning MERN stack and I want to contribute to open source projects. Can you please assign this task to me.

**Comment by rochita-sharma** [comment]
Can i work on this issue?
