### ISSUE TITLE
Many sections are repeating and contact form is also have some bug.

### ISSUE THREAD

**Issue by aman-netizen** [adithyapaib/Neomorphic-PortfolioTemplate#112]
Hi @adithyapaib many sections are repeating and also some error in contact form , it also scroll in x-axis . Can you please assign me this issue I what to contribute in this issue.

**Comment by adithyapaib** [comment]
> Hi @adithyapaib many sections are repeating and also some error in contact form , it also scroll in x-axis . Can you please assign me this issue I what to contribute in this issue.

Done
