### ISSUE TITLE
Issue : In contact section there is no social media icon like GitHub, LinkedIn, or many more

### ISSUE THREAD

**Issue by Aryan-kumar-mains** [adithyapaib/Neomorphic-PortfolioTemplate#118]

**Comment by Prerna-tech** [comment]
Kindly assign me this issue.  I want to fix it

**Comment by karar189** [comment]
please assign me this issue. I want to work on it

**Comment by arjita18** [comment]
Do you want the contact form exactly like the one one shown in the screenshots provided in the readme file?
