### ISSUE TITLE
Issue : whole website is overflows in x-direction and all the section lost it's position and many more problem

### ISSUE THREAD

**Issue by Aryan-kumar-mains** [adithyapaib/Neomorphic-PortfolioTemplate#125]

**Comment by nikita12c** [comment]
I have fixed the issue and set the overflow and height . Now this is perfectly fine and easy to scroll from top to bottom . Now the portfolio sections are not at all scattered , I have fixed them . **Take a look at the project changes screenshots below:**

- 
![git-after1](https://user-images.githubusercontent.com/66167434/136450467-3fadddcd-f3e3-4556-991f-9147b1be54a0.JPG)
![git-after2](https://user-images.githubusercontent.com/66167434/136450485-1c6965c6-bef9-4561-8120-afc3bcd56b6b.JPG)
![git-after3](https://user-images.githubusercontent.com/66167434/136450596-b3c7509a-50ba-462b-8356-c12092136c72.JPG)

Tell me whether I make the pull request of this change .
