### ISSUE TITLE
Issue: Contact Us Form Doesn't Match With The Whole Site

### ISSUE THREAD

**Issue by RayyanRNKJ** [adithyapaib/Neomorphic-PortfolioTemplate#135]
## Issues
- The whole form doesn't feel **Neomorphic**
- The input field's placeholder and labels are not aligned equally

![Screenshot 2021-10-09 at 12-42-08 Adithya Pai Web designer](https://user-images.githubusercontent.com/64679235/136648260-7c64c943-c695-4e4d-97b8-6cbddc04b6a5.png)

**Comment by Paawan9700** [comment]
@adithyapaib  can i work on this issue
