### ISSUE TITLE
The Contact Us Form Section needs modification

### ISSUE THREAD

**Issue by shagun0915** [adithyapaib/Neomorphic-PortfolioTemplate#136]
1. The form fields should be modified.
2. The whole Section can be made to look better by using some cards.

**Comment by Paawan9700** [comment]
hey @adithyapaib  can i work on this issue

**Comment by SujeetYT** [comment]
One more thing I would like to point is that adding just box shadow to all the edges of the container doesn't make it neomorphic design.
It should have partitioned in two parts like one side of for source of light and opposite side for the shadow

I'd like to raise the issue for this
