### ISSUE TITLE
Social Media Icons | Improvement 

### ISSUE THREAD

**Issue by pooja-gera** [adithyapaib/Neomorphic-PortfolioTemplate#19]
Greeetings! 

When we hover over the social media logos on the website, the color changes to #f53f2b. 
However, according to branding guidelines changing the color of these logos is not permitted. 

References: 
1. [GitHub Branding Guidelines](https://github.com/logos) - Changing the colors is not permitted 
2. [Twitter Branding Guidelines](https://about.twitter.com/content/dam/about-twitter/en/brand-toolkit/downloads/twitter-external-brand-guidelines-01272021.pdf) - Logo can only be used in either blue or white color and for black too permission is required from their team
3. [LinkedIn Branding Guidelines](https://brand.linkedin.com/downloads) - Changing the colors is not permitted 

Suggested Improvements: 
1. We can either add colored logos for all the aforementioned logos or upon hovering them change them to their original colors. However, the latter option does not fall in accordance with the Twitter Branding Guidelines. 
2.  We could use a mail icon / Gmail logo in place of the @ logo, it confused me too at first when I thought of what the icon is for. 

Do suggest any changes or further improvements.
It'll be super if I could be assigned this issue. 

Thanks and regards, 
Pooja Gera

**Comment by osamakhan552** [comment]
i can do that assign me this task

**Comment by pooja-gera** [comment]
Hello @osamakhan552 I am not the maintainer of this project, I was hoping to work on this and opened the issue for the maintainer's due consideration.

**Comment by agaveyonatan** [comment]
Hi, i have made some new change for the brand logo. I follow their brand guidelines. Maybe you can check my pull request. Thank you!

**Comment by adithyapaib** [comment]
assigined

**Comment by Paawan9700** [comment]
hey can you assign this issue to me.

**Comment by iteshgavel** [comment]
If issue is still there..Please assign to me. I will try my best.

**Comment by malvika-sinha** [comment]
Kindly assign me for this sir!
