### ISSUE TITLE
last panel not working properly 

### ISSUE THREAD

**Issue by Ayush-may** [adithyapaib/Neomorphic-PortfolioTemplate#197]
those icons should me placed over the box but something went wrong and this happened 

![image](https://github.com/adithyapaib/Neomorphic-PortfolioTemplate/assets/112775332/a0c22377-e8ef-4495-a2a7-28659a8479b1)

**Comment by adithyapaib** [comment]
Need to fix these issues

**Comment by Ayush-may** [comment]
check #198
