### ISSUE TITLE
Redesign Readme.md 

### ISSUE THREAD

**Issue by adithyapaib** [adithyapaib/Neomorphic-PortfolioTemplate#28]
Update the readme file and make the UI of the readme file better.

(If needed use the editor https://readme.so/)

**Comment by ramisha-anwer** [comment]
Hello! Kindly assign this issue to me. I will make the UI of readme file more attractive !

**Comment by adithyapaib** [comment]
Done 

> Hello! Kindly assign this issue to me. I will make the UI of readme file more attractive !

**Comment by jadhav-kunal** [comment]
Hey, I would like to contribute in making the Readme more attractive and minimal. Can you assign me?

**Comment by ramisha-anwer** [comment]
@adithyapaib Hey I have fixed this issue, kindly check my PR #45
