### ISSUE TITLE
Resume Button is unresponsive 

### ISSUE THREAD

**Issue by ramisha-anwer** [adithyapaib/Neomorphic-PortfolioTemplate#30]
Hey! Hope you're doing well. 
The resume button is unresponsive and does not open a resume upon clicking, I can add responsiveness to the button. The user can upload their resume  and It will open the pdf in a new tab upon clicking resume button.

**Comment by ramisha-anwer** [comment]
@adithyapaib kindly take a look into this and let me know if I can start working on it.

**Comment by tanvideshmukh29** [comment]
Can I work on it?
plz assign to me

**Comment by adithyapaib** [comment]
> Hey! Hope you're doing well. The resume button is unresponsive and does not open a resume upon clicking, I can add responsiveness to the button. The user can upload their resume and It will open the pdf in a new tab upon clicking resume button.

sure u can add the link to open the resume and @tanvideshmukh29  can add the target= _blank to open a new tab 
Please share the work among yourself @tanvideshmukh29  @ramisha-anwer  so that both of you' 'll get a PR.

**Comment by adithyapaib** [comment]
> Can I work on it? plz assign to me

sure

**Comment by developerNd** [comment]
please give Resume link to add to the resume button

**Comment by adithyapaib** [comment]
> please give Resume link to add to the resume button

resume.adithyapai.com

**Comment by ramisha-anwer** [comment]
@adithyapaib Issue fixed, kindly check my PR

**Comment by developerNd** [comment]
link added to the resume button which opens in a new tab check my PR

**Comment by jigarvyasidea** [comment]
Can I work on it?
plz assign to me

**Comment by Bluetoothworks** [comment]
Hi there! I've fixed the resume button. The link opens perfectly in a new tab. Please do see my changes and hope it can be merged
