### ISSUE TITLE
Reduce the size of icons and name in footer 

### ISSUE THREAD

**Issue by adithyapaib** [adithyapaib/Neomorphic-PortfolioTemplate#33]
Reduce the size of icons and name in footer

**Comment by rounit08** [comment]
can I take this?

**Comment by adithyapaib** [comment]
> can I take this?

Sure go ahead

**Comment by Paawan9700** [comment]
hey can you assign this issue to me.

**Comment by rounit08** [comment]
> > can I take this?
> 
> Sure go ahead

done :)

**Comment by MariamChowdhury** [comment]
Hi, Can you assign me this issue, please?

**Comment by Pruthvi-Tirmal** [comment]
can I take this issue, please assign me to fix this issue.
