### ISSUE TITLE
Add a Blog and Education Section in Portfolio

### ISSUE THREAD

**Issue by muhammadsuheer** [adithyapaib/Neomorphic-PortfolioTemplate#38]

**Comment by muhammadsuheer** [comment]
There is no blog and Education section in portfolio

**Comment by muhammadsuheer** [comment]
No blog and Education Section

**Comment by jadhav-kunal** [comment]
Hey, I would like to work on this! Can you let me know what information do you want me to put in blog and education section? Kindly assign me.

**Comment by adithyapaib** [comment]
Assigined please go ahead

**Comment by dubeyadarsh** [comment]
Hey, I want to contribute to this repo, Can u let me know what content needs to add to the blog and ed section? please assign me this task!

**Comment by adithyapaib** [comment]
> Hey, I want to contribute to this repo, Can u let me know what content needs to add to the blog and ed section? please assign me this task!

Assigined

**Comment by dubeyadarsh** [comment]
Bro , can u let me know what I have to fill in education and blog section
of this project ?

**Comment by arpit737** [comment]
Hi, I would like to work on this, can you please assign me this task, and also let me know what needs to be added to this new section.
