### ISSUE TITLE
In the Footer Section Social Links Email Not Working

### ISSUE THREAD

**Issue by DragonUncaged** [adithyapaib/Neomorphic-PortfolioTemplate#44]
Email Icon Is Not Responding.
When clicked Just Opening The Untitled new web page
![z1](https://user-images.githubusercontent.com/72241207/135728638-6b9857ee-a223-4172-8b58-c0f4f38c2da0.png)
when clicked !
![image](https://user-images.githubusercontent.com/72241207/135728667-fbe8e29d-a621-42bd-a8b5-2fdfbb9be652.png)

**Comment by Himanshu664** [comment]
I am working on this isssue
