### ISSUE TITLE
Fix broken Layout 

### ISSUE THREAD

**Issue by adithyapaib** [adithyapaib/Neomorphic-PortfolioTemplate#52]
The UI is broken after commits many PR's can anyone fix it?

**Comment by developerNd** [comment]
yes I know why UI is broken I can fix this

**Comment by developerNd** [comment]
Broken UI is fixed but Connect section need to be redesigned

**Comment by Pulkit007** [comment]
Hey @adithyapaib I have fixed this. Please have a look at my PR.
Here is the link https://github.com/adithyapaib/Neomorphic-PortfolioTemplate/pull/56

**Comment by adithyapaib** [comment]
Assigined pls PR

**Comment by coder483** [comment]
can i work on this

**Comment by adithyapaib** [comment]
> can i work on this

go ahead

**Comment by adithyapaib** [comment]
Fixed with pull #70
