### ISSUE TITLE
Layout is broken 

### ISSUE THREAD

**Issue by Mr-vabs** [adithyapaib/Neomorphic-PortfolioTemplate#61]
## Repeating Content

![Screenshot_2021-10-03-13-25-34-61](https://user-images.githubusercontent.com/33443357/135745198-d64e5f1f-9ba0-4e08-815c-e07cb3ba837f.jpg)

## Broken Layout

![Screenshot_2021-10-03-13-25-11-09_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/33443357/135745206-3732b577-1703-481a-a06a-453ebc760461.jpg)

![Screenshot_2021-10-03-13-25-00-16_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/33443357/135745208-e65be853-9166-41be-a3bf-4a91ef33fced.jpg)

## Same happened with desktop mode.

**Comment by Mr-vabs** [comment]
@adithyapaib 

One more thing , footer is absence from desktop of this project.

**Comment by Mr-vabs** [comment]
![Screenshot_2021-10-03-14-57-09-56_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/33443357/135747828-e43a8d7c-f22c-4c47-a7f8-8bfe8e598d70.jpg)

**Comment by adithyapaib** [comment]
Issue fixed with pull #70
