### ISSUE TITLE
Add a Projects Section 

### ISSUE THREAD

**Issue by muhammadsuheer** [adithyapaib/Neomorphic-PortfolioTemplate#65]
The project section should be add in portfolio

**Comment by adithyapaib** [comment]
Yes you are right

**Comment by alokmishra70** [comment]
Please assign me this issue

**Comment by And-Rahul** [comment]
Hello, I'm Rahul. I have good experience in making websites. Assign me this issue.

**Comment by malvika-sinha** [comment]
kindly assign me for this task !

**Comment by adithyapaib** [comment]
Assigined pls PR

**Comment by And-Rahul** [comment]
I think already there is a project section. @adithyapaib Can you specify more about the work we should do?
