### ISSUE TITLE
FIX the recent PROJECT HEADING

### ISSUE THREAD

**Issue by adithyapaib** [adithyapaib/Neomorphic-PortfolioTemplate#72]
Follow the same UI as the portfolio heading 

- reduced the size of recent projects
- Make it Lowercase capitalized
- fix project template

**Comment by dev-2k** [comment]
please assign me this task

**Comment by dev-2k** [comment]
I have fixed the issue. Please accept my pull request.

**Comment by shubhamhere** [comment]
please assign me this task : ) happy to contribute

**Comment by devikavarshney** [comment]
I can do this work.
Please assign it to me.

**Comment by AartiKushwaha** [comment]
I have fixed this issue, kindly check out #87 pull request. Thankyou

**Comment by Pruthvi-Tirmal** [comment]
Hey There, can you assign this to me I can fix this issue
