### ISSUE TITLE
Irregular size of icons in tools section

### ISSUE THREAD

**Issue by vikkastiwari** [adithyapaib/Neomorphic-PortfolioTemplate#77]
There is an irregular size of Icons in the tools section. which I can see is of 32px X 32px. Where the Icons under programming and design is of 48px X 48px.

And as the Icons are fetched from the server. So @adithyapaib  guide me through this how I can take it further to resolve the issue.

**Comment by Paawan9700** [comment]
hey kindly assign this issue to me, i will definitely resolve it.

**Comment by shubhamhere** [comment]
hey kindly assign this issue to me,  will definitely resolve it. happy to contribute : )

**Comment by Paawan9700** [comment]
@adithyapaib i have solved the issue #76 PR kindly merge it and if there is any conflicts then let me know.
