### ISSUE TITLE
Remove .vscode folder

### ISSUE THREAD

**Issue by adithyapaib** [adithyapaib/Neomorphic-PortfolioTemplate#83]
Remove obsolete folders and files

**Comment by khushii05** [comment]
Hey! Hope you're doing well. Can you assign this issue to me. I can work on this

**Comment by arpit737** [comment]
Hey can you assign me this issue, I can work on this

**Comment by abdul-sohail24** [comment]
Hey there, I could work on this issue. Can you please assign it to me?

**Comment by Pruthvi-Tirmal** [comment]
Hey  there, i can fix this, could you please assign it to me

**Comment by swayamg20** [comment]
hello there, can you assign me this issue, I am starting as an open-source developer and I think this might be a good start.
