### ISSUE TITLE
Contact us Form in Footer.

### ISSUE THREAD

**Issue by muhammadsuheer** [adithyapaib/Neomorphic-PortfolioTemplate#86]
It will be  much better for a viewer to  directly leave a message  by contact us form

**Comment by abdul-sohail24** [comment]
Hey there, I can add the Contact Us Form, could you please assign it to me

**Comment by abdul-sohail24** [comment]
> Hey there, I can add the Contact Us Form, could you please assign it to me
 
I've completed this issue, kindly refer to my PR #88

**Comment by adithyapaib** [comment]
> > Hey there, I can add the Contact Us Form, could you please assign it to me
> 
> I've completed this issue, kindly refer to my PR #88

Merge conflicts
