### ISSUE TITLE
FIX Header and project

### ISSUE THREAD

**Issue by adithyapaib** [adithyapaib/Neomorphic-PortfolioTemplate#89]
PLS use the tag [FIXED HEADER]  and [FIXED PROJECT]  in the PR  title .

- Change the font of the headings PORTFOLIO: make it smaller and only capitalize the starting letter or pls revert it back to how it was in the beginning 
-reduced the animation time of connecting me 
-Fix over flow issue of project and image

**Comment by Paawan9700** [comment]
hey i would like to work on this issue. can you assign it to me.

**Comment by GoyalRohan** [comment]
I would like to work on this issue ??
Can you plz assign it to me?

**Comment by dishari-ae** [comment]
@adithyapaib Please assign this issue to me

**Comment by Shivabhai319** [comment]
Can You Please Assignt to me?

**Comment by adithyapaib** [comment]
Done

**Comment by GoyalRohan** [comment]
@adithyapaib Can you please clear the instructions?
I can't understand your instructions clearly

The portfolio is already capitalize
