### ISSUE TITLE
Some padding required at the footer and anchor link line to be removed with having icon hover

### ISSUE THREAD

**Issue by AnshumanDhiman** [adithyapaib/Neomorphic-PortfolioTemplate#9]

**Comment by adithyapaib** [comment]
Sure assigined u

**Comment by artimanputra** [comment]
hey, I would like to work on this.

**Comment by tanvideshmukh29** [comment]
I would love to contribute on this issue ...plz assign this to me.

**Comment by adithyapaib** [comment]
> hey, I would like to work on this.

assigned

**Comment by adithyapaib** [comment]
> I would love to contribute on this issue ...plz assign this to me.

assigned

**Comment by Sudipta2002** [comment]
Please assign me I can do this .

**Comment by adithyapaib** [comment]
> Please assign me I can do this .

Done

**Comment by Paawan9700** [comment]
hey kindly assign it to me. i will surely resolve it.

**Comment by adithyapaib** [comment]
> hey kindly assign it to me. i will surely resolve it.

Done

**Comment by ayushjain27** [comment]
Please assign me

**Comment by Ankita-Nandkumar-Patil** [comment]
please assign it to me, i'll fix it..!

**Comment by Ritika457** [comment]
Can you please assign this issue to me. I can fix this.

**Comment by Paawan9700** [comment]
@adithyapaib i have resolved the issue. please check the #76 PR and kindly merge it.
