### ISSUE TITLE
Back to top button is not working

### ISSUE THREAD

**Issue by nafladiva** [adithyapaib/Neomorphic-PortfolioTemplate#91]
Back to top button is not working, I would like to fix this issue and add some styling to this button link!

**Comment by AbhishekSharma-86** [comment]
I want to work on this issue, please assign this issue to me

**Comment by adithyapaib** [comment]
Go ahead

**Comment by Jyoti-prakash-rout** [comment]
I would like to work on this issue. Can you please assign me?

**Comment by Sudipta2002** [comment]
Please assign me i can do this with attractive style

**Comment by KeeganC09** [comment]
Please assign this issue to me, I'll fix this bug and style the Back To Top button too

**Comment by KeeganC09** [comment]
Please assign this issue to me, I'll fix this bug and style the Back To Top button too
