### ISSUE TITLE
FIX Site's layout and Duplicates.

### ISSUE THREAD

**Issue by RayyanRNKJ** [adithyapaib/Neomorphic-PortfolioTemplate#97]
![Screenshot 2021-10-05 at 07-57-44 Adithya Pai Web designer](https://user-images.githubusercontent.com/64679235/135951082-182754e6-8806-4f5d-9d27-b39013fcd546.png)
![Screenshot 2021-10-05 at 07-58-20 Adithya Pai Web designer](https://user-images.githubusercontent.com/64679235/135951156-0d960e9d-db3f-4a45-b92d-f4a806541eb3.png)
![Screenshot 2021-10-05 at 07-58-56 Adithya Pai Web designer](https://user-images.githubusercontent.com/64679235/135951195-2ae308de-10b4-44ed-b77d-ef03c9669288.png)
![Screenshot 2021-10-05 at 07-59-35 Adithya Pai Web designer](https://user-images.githubusercontent.com/64679235/135951212-13fa2d64-5e21-4e42-83d2-cfafad3e5d62.png)

**Comment by adithyapaib** [comment]
Pls PR

**Comment by RayyanRNKJ** [comment]
Ok Sure
